#! /bin/sh
# Init script to start ppusquirt

case "$1" in
	start|"")
		if [ "$VERBOSE" != no ]
		then
			printf "Starting PPUsquirt..."
		fi
		modprobe uinput
		cd /opt/PiPU
		./ppusquirt &


		[ "$VERBOSE" != no ] && echo "done."
		;;
	stop)
		killall ppusquirt
		;;
	*)
		echo "Usage: ppusquirt {start|stop}" >&2
		exit 1
		;;
esac
